spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/EMPLOYEE_MANAGEMENT_SYSTEM?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: root
    password: 1234
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    #For MySQL 5
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true


  #Passwords for the first 2 users that are auto initialized in the DataBase: Admin and User
  EMPLOYEE MANAGEMENT SYSTEM:
    boss:
      defaultPasswordForBoss: test
    moderator:
      defaultPasswordForModerator: test
    employee:
      defaultPasswordForEmployee: test